python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 5
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 10
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 15
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 20
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 25
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 30
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 35
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 40
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 45
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 50
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 55
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 60
python3 img_process.py --image Daan_B2_crop.png --minLineLength 10 --maxLineGap 200 --line_th 70